[FIX] Change to INSTANCE_LOCK for consistency
git-svn-id: https://svn.code.sf.net/p/tikiwiki/code/trunk@48114 b456876b-0849-0410-b77d-98878d47e9d5

diff --git a/doc/devtools/tim/tim b/doc/devtools/tim/tim
--- a/doc/devtools/tim/tim
+++ b/doc/devtools/tim/tim
@@ -90,9 +90,9 @@ destroy()
 {
 	mysql -e "DROP DATABASE $DB;" && echo "DATABASE $DB suppressed" || echo "ERROR: database $DB not suppressed"
 	rm -r $INSTANCE_DIR && echo "FILES in $INSTANCE_DIR suppressed" || echo "ERROR: FILES in $INSTANCE_DIR not suppressed"
-	if [[ -f $LOCKSDIR/lock_${TUSERID}_${ID} ]] 
+	if [[ -f $INSTANCE_LOCK ]] 
 	then
-		rm $LOCKSDIR/lock_${TUSERID}_${ID} && echo "LOCK file removed" || echo "ERROR: LOCK file could not be removed"
+		rm $INSTANCE_LOCK && echo "LOCK file removed" || echo "ERROR: LOCK file could not be removed"
 	fi
 }
 
@@ -172,7 +172,7 @@ info()
 			elif [[ $(ls -d -1 *-${TUSERID}-${ID} 2>/dev/null | wc -l ) == 1 ]]
 			then 
 				SUBDOMAIN=$(ls -d -1 *-${TUSERID}-${ID})
-				if [[ -e $LOCKSDIR/lock_${TUSERID}_${ID} ]]
+				if [[ -e $INSTANCE_LOCK ]]
 				then
 					echo "STATUS: BUILDING"
 				else
@@ -189,9 +189,9 @@ info()
 				SUBDOMAIN=$(ls -d -1 *-${TUSERID}-${ID})
 				if [[ ! -z $TUSER ]] && [[ -d "$TUSER-$TUSERID-$ID" ]]
 				then
-					if [[ -e $LOCKSDIR/lock_${TUSERID}_${ID} ]]
+					if [[ -e $INSTANCE_LOCK ]]
 					then
-						BEINGBUILT=$(/bin/cat "${LOCKSDIR}/lock_${TUSERID}_${ID}")
+						BEINGBUILT=$(/bin/cat "${INSTANCE_LOCK}")
 						if [[ "${BEINGBUILT}" == "${TUSER}" ]]
 						then
 							echo "STATUS: BUILDING"
@@ -229,7 +229,7 @@ case ${COMMAND} in
 		echo "SITE: ${SUBDOMAIN}.show.tikiwiki.org "
 		echo "LOG: http://${SUBDOMAIN}.show.tikiwiki.org/install_log.txt (available after a delay)"
 		# This is simply too long for synchronous feedback
-		nohup $PREFIX/tim-create -t "$SVNTAG" -u "$TUSER" -U "$TUSERID" -i "$ID" 1>$INSTANCE_DIR/install_log.txt 2>&1 &
+		nohup $PREFIX/tim-create -t "$SVNTAG" -u "$TUSER" -U "$TUSERID" -i "$ID"
 		exit 0
 		;;
 	destroy)
diff --git a/doc/devtools/tim/tim-create b/doc/devtools/tim/tim-create
--- a/doc/devtools/tim/tim-create
+++ b/doc/devtools/tim/tim-create
@@ -71,9 +71,9 @@ debug()
 
 create()
 {
-	if [[ -e $LOCKSDIR/lock_${TUSERID}_${ID} ]] ; then echo "FAIL: Lock file already exists. Another install is being performed"; exit 1; fi
+	if [[ -e $INSTANCE_LOCK ]] ; then echo "FAIL: Lock file already exists. Another install is being performed"; exit 1; fi
 	#TODO: remove stale locks
-	echo "${TUSER}" > "${LOCKSDIR}/lock_${TUSERID}_${ID}" || (echo "FAIL: Failed to create lock file ${LOCKSDIR}/lock_${TUSERID}_${ID}"; exit 1)
+	echo "${TUSER}" > "${INSTANCE_LOCK}" || (echo "FAIL: Failed to create lock file ${INSTANCE_LOCK}"; exit 1)
 
 	mkdir $INSTANCE_DIR || echo "FAIL: $INSTANCE_DIR not created"
 
@@ -153,7 +153,7 @@ EOT
 UPDATE tiki_pages SET data=CONCAT('{REMARKSBOX(type="information" title="Show community server" close="y")}${infotext}{REMARKSBOX} ',data) WHERE page_id=1;
 EOQ
 
-	/bin/rm $LOCKSDIR/lock_${TUSERID}_${ID} || (echo "FAIL: Failed to suppress lock file $LOCKSDIR/lock_${TUSERID}_${ID}"; exit 1)
+	/bin/rm $INSTANCE_LOCK || (echo "FAIL: Failed to suppress lock file $INSTANCE_LOCK"; exit 1)
 }
 
 echo "CREATION START - watch ${SUBDOMAIN}.show.tikiwiki.org "
