[REM] password field tidy-up
git-svn-id: https://svn.code.sf.net/p/tikiwiki/code/branches/16.x@60210 b456876b-0849-0410-b77d-98878d47e9d5

diff --git a/doc/devtools/tim/tim b/doc/devtools/tim/tim
--- a/doc/devtools/tim/tim
+++ b/doc/devtools/tim/tim
@@ -129,7 +129,7 @@ reset()
 	fi
 	[[ -z $DB_DETECTED ]] && echo "WARNING: Could not detect database for instance"
 	if [[ -z "${APASSWORD}" ]]; then APASSWORD="12345"; fi
-	mysql -e "UPDATE users_users SET password='admin', hash= md5('${APASSWORD}') WHERE login='admin';" $DB_DETECTED && echo "SUCCESS: Admin password reset to ${APASSWORD} in database ${DB_DETECTED}" || echo "ERROR: admin password not reset in database ${DB_DETECTED}"
+	mysql -e "UPDATE users_users SET hash= md5('${APASSWORD}') WHERE login='admin';" $DB_DETECTED && echo "SUCCESS: Admin password reset to ${APASSWORD} in database ${DB_DETECTED}" || echo "ERROR: admin password not reset in database ${DB_DETECTED}"
 }
 
 update()
